#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-Rsolnp
Version  : 2.0.1
Release  : 45
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/Rsolnp_2.0.1.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/Rsolnp_2.0.1.tar.gz
Summary  : General Non-Linear Optimization
Group    : Development/Tools
License  : GPL-2.0
Requires: R-Rsolnp-lib = %{version}-%{release}
Requires: R-Rcpp
Requires: R-RcppArmadillo
Requires: R-future.apply
Requires: R-numDeriv
Requires: R-truncnorm
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : R-RcppArmadillo-dev
BuildRequires : R-future.apply
BuildRequires : R-numDeriv
BuildRequires : R-truncnorm
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-Rsolnp package.
Group: Libraries

%description lib
lib components for the R-Rsolnp package.


%prep
%setup -q -n Rsolnp
pushd ..
cp -a Rsolnp buildavx2
popd
pushd ..
cp -a Rsolnp buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1751292513

%install
export SOURCE_DATE_EPOCH=1751292513
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Rsolnp/DESCRIPTION
/usr/lib64/R/library/Rsolnp/INDEX
/usr/lib64/R/library/Rsolnp/Meta/Rd.rds
/usr/lib64/R/library/Rsolnp/Meta/features.rds
/usr/lib64/R/library/Rsolnp/Meta/hsearch.rds
/usr/lib64/R/library/Rsolnp/Meta/links.rds
/usr/lib64/R/library/Rsolnp/Meta/nsInfo.rds
/usr/lib64/R/library/Rsolnp/Meta/package.rds
/usr/lib64/R/library/Rsolnp/Meta/vignette.rds
/usr/lib64/R/library/Rsolnp/NAMESPACE
/usr/lib64/R/library/Rsolnp/R/Rsolnp
/usr/lib64/R/library/Rsolnp/R/Rsolnp.rdb
/usr/lib64/R/library/Rsolnp/R/Rsolnp.rdx
/usr/lib64/R/library/Rsolnp/doc/index.html
/usr/lib64/R/library/Rsolnp/doc/introduction.R
/usr/lib64/R/library/Rsolnp/doc/introduction.Rmd
/usr/lib64/R/library/Rsolnp/doc/introduction.html
/usr/lib64/R/library/Rsolnp/doc/test_suite.R
/usr/lib64/R/library/Rsolnp/doc/test_suite.Rmd
/usr/lib64/R/library/Rsolnp/doc/test_suite.html
/usr/lib64/R/library/Rsolnp/help/AnIndex
/usr/lib64/R/library/Rsolnp/help/Rsolnp.rdb
/usr/lib64/R/library/Rsolnp/help/Rsolnp.rdx
/usr/lib64/R/library/Rsolnp/help/aliases.rds
/usr/lib64/R/library/Rsolnp/help/paths.rds
/usr/lib64/R/library/Rsolnp/html/00Index.html
/usr/lib64/R/library/Rsolnp/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/Rsolnp/libs/Rsolnp.so
/V4/usr/lib64/R/library/Rsolnp/libs/Rsolnp.so
/usr/lib64/R/library/Rsolnp/libs/Rsolnp.so
